version: '3.3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/PG_DATABASE
    ports:
      - ${PG_LOCAL_PORT}:${PG_PORT}
  app:
    container_name: graph-docker
    build: 
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - ${API_LOCAL_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - PG_CONNECTION=${PG_CONNECTION}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_LOCAL_PORT=${PG_LOCAL_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_HOST=postgres
